#
# GitHub actions for checking the installation of MW4 through scripts
#
# v 1.0, Michael Wuertenberger
#
name: test_scripts_pypi_raspi

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  gh: 'https://raw.githubusercontent.com/mworion/MountWizzard4/master/support/3.0/'

on:
  push:
    # Run this action on the trigger event when specific files are touched
    paths:
      - '.github/workflows/test_scripts_pypi_raspi.yml'
      - 'support/**'
      - 'setup.py'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64]
        include:
        - arch: aarch64
          cpu: cortex-a53
          base_image: dietpi:rpi_armv8_bullseye
          cpu_info: cpuinfo/raspberrypi_zero2_w_arm64

    steps:
      - uses: pguyot/arm-runner-action@v2
        with:
          image_additional_mb: 8192
          base_image: ${{ matrix.base_image }}
          cpu: ${{ matrix.cpu }}
          cpu_info: ${{ matrix.cpu_info }}
          commands: |
            ls -la
            sudo apt-get update
            sudo apt-get -y upgrade
            apt-get install -y python3.10 python3-venv python3-pip
            apt-get install -y pacman
            python3 --version
            python3 -m venv venv
            source ./venv/bin/activate
            pip list
            pacman -S python-pyqt5
            pip install mountwizzard4==3.0.1a0
            cat ./log/mw4*.log
            ls -la
