############################################################
#
#       #   #  #   #   #    #
#      ##  ##  #  ##  #    #
#     # # # #  # # # #    #  #
#    #  ##  #  ##  ##    ######
#   #   #   #  #   #       #
#
# Python-based Tool for interaction with the 10micron mounts
# GUI with PySide6
#
# written in python3, (c) 2019-2025 by mworion
# Licence APL2.0
#
###########################################################

name: test_scripts_pypi

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: True

env:
  gh: 'https://raw.githubusercontent.com/mworion/InstallerMW4/main/support/'
  version: '4.0.0a41'

on:
  push:
    # Run this action on the trigger event when specific files are touched
    paths:
      - '.github/workflows/test_scripts_pypi.yml'
      - 'pyproject.toml'

jobs:
  
  install_windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2022, windows-2025 ]
        python-version: [ '3.11', '3.13' ]

    steps:
      - name: install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
     
      - name: MountWizzard4 Install
        continue-on-error: true
        shell: cmd
        run: |
          uv pip install mountwizzard4==${{ env.version }}
       
      - name: Run MountWizzard4
        run: |
          uv run mw4 -t
          dir
  
  install_ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        python-version: [ '3.11', '3.13' ]
    
    steps:
      - name: Install Head
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libxkbcommon-x11-0 x11-utils libxcb-icccm4
          sudo apt-get install -y libxcb-image0 libxcb-keysyms1 libxcb-randr0
          sudo apt-get install -y libxcb-render-util0 libpulse-mainloop-glib0
          sudo apt-get install -y libx11-xcb1 libxcb-xinerama0 libxcb-xkb1
          sudo apt-get install -y libxcb-keysyms1 ffmpeg libsm6 libxext6
          sudo apt-get install -y libxcb-cursor0 libegl1-mesa
          
      - name: install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: MountWizzard4 Install
        continue-on-error: true
        run: |
          uv pip install mountwizzard4==${{ env.version }}

      - name: Run MountWizzard4
        continue-on-error: true
        run: |
          xvfb-run uv run mw4 -t 
          ls -la
 
          
  install_macOS:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15, macos-15-intel , macos-26]
        python-version: [ '3.11', '3.13' ]
    
    steps:
      - name: install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: MountWizzard4 Install
        continue-on-error: true
        run: |
          uv pip install mountwizzard4==${{ env.version }}
          
      - name: MountWizzard4 Run
        continue-on-error: true
        run: |
          uv run mw4 -t
          ls -la
          