#
# v1.0, Michael Wuertenberger
#
name: unit_macOS
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  branch: '3.2.0'
  
on:
  push:
    # Run this action on the trigger event when specific files are touched
    paths:
      - 'mw4/**'
      - 'tests/unit_tests/**'
      - 'setup.py'
      - '.github/workflows/unit_macOS.yml'
      - '.github/actions/build_package/action.yml'
      - '.github/actions/setup_test/action.yml'
jobs:
  build_package:
    #
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.branch}}
          
      - name: build package
        uses: ./.github/actions/build_package

  run_tests_macos_1:
    #
    needs: build_package
    runs-on: macos-13
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test
  
      - name: running_unit_tests
        run: |
          python -m pip install pyqt5-qt5==5.15.2
          python -m pip install pyqt3d-qt5==5.15.2
          pytest tests/unit_tests/zLoader
          pytest tests/unit_tests/zUpdate
          pytest tests/unit_tests/zMainApp
          pytest tests/unit_tests/gui/mainWindow

  run_tests_macos_2a:
    #
    needs: build_package
    runs-on: macos-13
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test

      - name: running_unit_tests
        run: |
          python -m pip install pyqt3d-qt5==5.15.2
          python -m pip install pyqt5-qt5==5.15.2
          pytest tests/unit_tests/base
          pytest tests/unit_tests/logic
          pytest tests/unit_tests/mountcontrol
          pytest tests/unit_tests/indibase
          pytest tests/unit_tests/gui/utilities

  run_tests_macos_2b:
    #
    needs: build_package
    runs-on: macos-13
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test

      - name: running_unit_tests
        run: |
          python -m pip install pyqt5-qt5==5.15.2
          python -m pip install pyqt3d-qt5==5.15.2
          pytest tests/unit_tests/gui/extWindows

  run_tests_macos_3:
    #
    needs: build_package
    runs-on: macos-13
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test
  
      - name: running_unit_tests
        run: |
          python -m pip install pyqt5-qt5==5.15.2
          python -m pip install pyqt3d-qt5==5.15.2
          pytest tests/unit_tests/gui/mainWmixin1

  run_tests_macos_4:
    #
    needs: build_package
    runs-on: macos-13
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test
  
      - name: running_unit_tests
        run: |
          python -m pip install pyqt5-qt5==5.15.2
          python -m pip install pyqt3d-qt5==5.15.2
          pytest tests/unit_tests/gui/mainWmixin2

  run_tests_macos_5:
    #
    needs: build_package
    runs-on: macos-13
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test
  
      - name: running_unit_tests
        run: |
          python -m pip install pyqt5-qt5==5.15.2
          python -m pip install pyqt3d-qt5==5.15.2
          pytest tests/unit_tests/gui/mainWmixin3
